### ISSUE TITLE
Doesn't work for me (Windows 10)

### ISSUE THREAD

**Issue by angramainyuu** [ndbiaw/jewcob-fakku-downloader#1]
Getting this error:

E:\Hosted Torrents\jewcob-fakku-downloader-main>py main.py
Cookies file(cookies.json) are not detected. Please, login in next step for generate cookie for next runs.
Initializing browser
Connecting to chromedriver

Press Enter to continue after you login...
Connecting to chromedriver
Traceback (most recent call last):
  File "E:\Hosted Torrents\jewcob-fakku-downloader-main\main.py", line 215, in <module>
    main()
  File "E:\Hosted Torrents\jewcob-fakku-downloader-main\main.py", line 206, in main
    loader.init_browser(auth=True, gui=args.gui)
  File "E:\Hosted Torrents\jewcob-fakku-downloader-main\downloader.py", line 541, in init_browser
    self.__set_cookies()
  File "E:\Hosted Torrents\jewcob-fakku-downloader-main\downloader.py", line 606, in __set_cookies
    cookie["expiry"] = int(cookie["expiry"])
                           ~~~~~~^^^^^^^^^^
KeyError: 'expiry'
Exception ignored in: <function Chrome.__del__ at 0x0000019C3177A340>
Traceback (most recent call last):
  File "C:\Users\Umi\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in __del__
    self.quit()
  File "C:\Users\***\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
    time.sleep(0.1)
OSError: [WinError 6] **The handle is invalid**

You should probably also include selenium==4.9.0 in the requirements.txt file as undetected-chromedriver doesn't work properly anymore on 4.13.0

**Comment by nayumiDEV** [comment]
Script tested on Python 3.10, Chrome v110. I currently don't have time to test.
